pom6 = sqldf("select commits, count(proj) as numproj from pom5 group by commits order by commits")
pom7 = sqldf("select * from pom6 where commits > 0")
ggplot(data=pom7, aes(x=commits, y=numproj), group = commits) + geom_line() + xlim(0,100) + labs(y = "number of projects")
ggplot(data=pom7, aes(x=commits, y=numproj), group = commits) + geom_line() + xlim(0,100) + ylim(0,1000)+ labs(y = "number of projects")
pom8 = sqldf("select devs, count(proj) as numproj from pom5 group by devs order by devs")
ggplot(data=pom8, aes(x=devs, y=numproj), group = devs) + geom_line()
pom10 = sqldf("select * from pom5 where commits > 25")
final = sqldf("select pm.proj, pm.name, pm.month, pm.phase from pm, pom10 where pm.proj = pom10.proj")
write.csv(final, "final.csv")
pom11 = sqldf("select devs, count(proj) as numproj from pom10 group by devs order by devs")
ggplot(data=pom11, aes(x=devs, y=numproj), group = devs) + geom_line() + labs(y = "number of projects")
pom10 = sqldf("select * from pom10 where devs > 4")
